name: Rebase-upstream

on:
  push:
    branches:
      - master
  schedule:
    - cron: 30 19 * * *
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git config
      run : |
        git config --global user.email "27893441+liyufan@users.noreply.github.com"
        git config --global user.name "Johnson Lee"

    - name: Load upstream commits
      run: |
        MY_COMMIT=$(git rev-parse HEAD)
        # In case of conflict caused by upstream force push
        # we need to reset to the 50th commit and rebase on top of the upstream master
        git reset --hard HEAD~50
        git remote add upstream https://github.com/coolsnowwolf/lede
        git pull upstream master --rebase
        git cherry-pick $MY_COMMIT

    - name: Push Commits
      run: git push -f
